In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\abhil\anaconda3\lib\site-packages (4.17.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\abhil\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\abhil\anaconda3\lib\site-packages (from selenium) (0.24.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\abhil\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\abhil\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\abhil\anaconda3\lib\site-packages (from selenium) (4.9.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\abhil\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\abhil\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\abhil\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\abhil\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\abhil\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\abhil\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\abhil\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\abhil\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\abhil\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\abhil\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [149]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [85]:
driver = webdriver.Chrome()
driver.get("https://www.shine.com/")
search_eng = driver.find_element(By.XPATH,"/html/body/div/header/div[3]/div/div/div[1]/div/input")
search_eng.click()
time.sleep(5)
designation = driver.find_element(By.XPATH,"/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[1]/ul/li[1]/div/input")
designation.send_keys('Data Analyst')
location = driver.find_element(By.XPATH,"/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[1]/ul/li[2]/div/input")
location.send_keys('Bangalore')
search = driver.find_element(By.XPATH,"/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[2]/div/button")
search.click()

In [56]:
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

In [57]:
comp_name_tags = driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_cName__mYnow"]')
comp_name_tags10 = comp_name_tags[:10]

for i in comp_name_tags10:
    name = i.text
    company_name.append(name)
    
company_name

['ara resources private limited',
 'diraa hr services hiring for mncs',
 'yogita staffing solution',
 'techno endura',
 'future solution centre',
 'boyen haddin consulting and technol...',
 'boyen haddin consulting and technol...',
 'boyen haddin consulting and technol...',
 'boyen haddin consulting and technol...',
 'quiscon biotech']

In [58]:
title_tags = driver.find_elements(By.XPATH,'//h2[@itemprop="name"]')
title_tags10 = title_tags[:10]

for i in title_tags10:
    title = i.text
    job_title.append(title)
    
job_title

['Lead Data Analyst',
 'Data Analyst',
 'Vacancy For Data Analyst',
 'Clinical Data Analyst',
 'Data Management',
 'Data Modeler data',
 'Data Modeller',
 'Data Modeler Bangalore',
 'Data Modeler',
 'Clinical Data Analyst']

In [59]:
location_tags = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
location_tags10 = location_tags[:10]
for i in location_tags10:
    location = i.text
    job_location.append(location)
    
job_location

['Bangalore',
 'Bangalore\n+3',
 'Bangalore\n+14',
 'Bangalore\n+6',
 'Bangalore\n+18',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore',
 'Bangalore\n+4']

In [60]:
experience_tags = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_jobIcon__3FB1t"]')
experience_tags10 = experience_tags[:10]
for i in experience_tags10:
    exp = i.text
    experience_required.append(exp)
    
experience_required

['4 to 9 Yrs',
 '0 to 1 Yr',
 '0 to 3 Yrs',
 '0 to 1 Yr',
 '15 to >25 Yrs',
 '3 to 6 Yrs',
 '3 to 6 Yrs',
 '3 to 6 Yrs',
 '3 to 6 Yrs',
 '0 to 2 Yrs']

In [61]:
df = pd.DataFrame({'Job Title':job_title,'Job Location':job_location,'Company Name':company_name,'Experience':experience_required})
df

,Job Title,Job Location,Company Name,Experience
0,Lead Data Analyst,Bangalore,ara resources private limited,4 to 9 Yrs
1,Data Analyst,Bangalore\n+3,diraa hr services hiring for mncs,0 to 1 Yr
2,Vacancy For Data Analyst,Bangalore\n+14,yogita staffing solution,0 to 3 Yrs
3,Clinical Data Analyst,Bangalore\n+6,techno endura,0 to 1 Yr
4,Data Management,Bangalore\n+18,future solution centre,15 to >25 Yrs
5,Data Modeler data,Bangalore,boyen haddin consulting and technol...,3 to 6 Yrs
6,Data Modeller,Bangalore,boyen haddin consulting and technol...,3 to 6 Yrs
7,Data Modeler Bangalore,Bangalore,boyen haddin consulting and technol...,3 to 6 Yrs
8,Data Modeler,Bangalore,boyen haddin consulting and technol...,3 to 6 Yrs
9,Clinical Data Analyst,Bangalore\n+4,quiscon biotech,0 to 2 Yrs

In [70]:
driver = webdriver.Chrome()
driver.get("https://www.shine.com/")
search_eng = driver.find_element(By.XPATH,"/html/body/div/header/div[3]/div/div/div[1]/div/input")
search_eng.click()
time.sleep(5)
designation2 = driver.find_element(By.XPATH,"/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[1]/ul/li[1]/div/input")
designation2.send_keys('Data Scientist')
location2 = driver.find_element(By.XPATH,"/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[1]/ul/li[2]/div/input")
location2.send_keys('Bangalore')
search = driver.find_element(By.XPATH,"/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[2]/div/button")
search.click()

In [82]:
job_title2=[]
job_location2=[]
company_name2=[]
experience_required2=[]

In [83]:
comp_name_tags = driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_cName__mYnow"]')
comp_name_tags10 = comp_name_tags[:10]

for i in comp_name_tags10:
    name = i.text
    company_name2.append(name)
    
company_name2

['gujarat facility services hiring fo...',
 'renuka interprises',
 'renuka interprises',
 'renuka interprises',
 'acme services private limited',
 'ltimindtree limited',
 'fractal',
 'yogita staffing solution',
 'neostats',
 'aereo']

In [84]:
title_tags = driver.find_elements(By.XPATH,'//h2[@itemprop="name"]')
title_tags10 = title_tags[:10]

for i in title_tags10:
    title = i.text
    job_title2.append(title)
    
job_title2

['ML Data Scientist',
 'Data Scientist Urgent Vacancy',
 'Data Scientist Recruitment',
 'Data Scientist Recruitment',
 'Data Scientist',
 'Data Scientist',
 'Lead Data Scientist/ Principal Data Scientist',
 'Vacancy For Data Scientist Fresher and Experience',
 'Senior Data Scientist',
 'Lead Data Scientist']

In [85]:
location_tags = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
location_tags10 = location_tags[:10]
for i in location_tags10:
    location = i.text
    job_location2.append(location)
    
job_location2

['Bangalore\n+3',
 'Bangalore\n+15',
 'Bangalore\n+15',
 'Bangalore\n+15',
 'Bangalore\n+4',
 'Bangalore',
 'Bangalore\n+1',
 'Bangalore\n+14',
 'Bangalore\n+1',
 'Bangalore\n+1']

In [86]:
experience_tags = driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_jobIcon__3FB1t"]')
experience_tags10 = experience_tags[:10]
for i in experience_tags10:
    exp = i.text
    experience_required2.append(exp)
    
experience_required2

['5 to 8 Yrs',
 '0 to 4 Yrs',
 '0 to 4 Yrs',
 '0 to 4 Yrs',
 '3 to 5 Yrs',
 '6 to 8 Yrs',
 '5 to 9 Yrs',
 '0 to 3 Yrs',
 '7 to 11 Yrs',
 '7 to 10 Yrs']

In [87]:
df2 = pd.DataFrame({'Job Title':job_title2,'Job Location':job_location2,'Company Name':company_name2,'Experience':experience_required2})
df2

,Job Title,Job Location,Company Name,Experience
0,ML Data Scientist,Bangalore\n+3,gujarat facility services hiring fo...,5 to 8 Yrs
1,Data Scientist Urgent Vacancy,Bangalore\n+15,renuka interprises,0 to 4 Yrs
2,Data Scientist Recruitment,Bangalore\n+15,renuka interprises,0 to 4 Yrs
3,Data Scientist Recruitment,Bangalore\n+15,renuka interprises,0 to 4 Yrs
4,Data Scientist,Bangalore\n+4,acme services private limited,3 to 5 Yrs
5,Data Scientist,Bangalore,ltimindtree limited,6 to 8 Yrs
6,Lead Data Scientist/ Principal Data Scientist,Bangalore\n+1,fractal,5 to 9 Yrs
7,Vacancy For Data Scientist Fresher and Experience,Bangalore\n+14,yogita staffing solution,0 to 3 Yrs
8,Senior Data Scientist,Bangalore\n+1,neostats,7 to 11 Yrs
9,Lead Data Scientist,Bangalore\n+1,aereo,7 to 10 Yrs

In [111]:
driver = webdriver.Chrome()
driver.get("https://www.shine.com/")
search_eng = driver.find_element(By.XPATH,"/html/body/div/header/div[3]/div/div/div[1]/div/input")
search_eng.click()
time.sleep(5)
designation3 = driver.find_element(By.XPATH,"/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[1]/ul/li[1]/div/input")
designation3.send_keys('Data Scientist')
search = driver.find_element(By.XPATH,"/html/body/div/div[4]/div/div[2]/div[2]/div[1]/form/div/div[2]/div/button")
search.click()

In [117]:
location3_1 = driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/div[3]/div/div[1]/div/div[2]/div/ul/li[1]/button")
location3_1.click()
location3 = driver.find_element(By.XPATH,"/html/body/div[2]/div/div/div/div[3]/div/div/div/ul/li[13]/span/label")
location3.click()
show_results1 = driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div/div[4]/button[2]')
show_results1.click()

salary3 = driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/div[3]/div/div[1]/div/div[2]/div/ul/li[3]/button")
salary3.click()
salary_check = driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div/div[3]/div/div/div/ul/li[3]/span')
salary_check.click()
show_results = driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div/div[4]/button[2]')
show_results.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div/div/div/div[3]/div/div/div/ul/li[13]/span/label"}
  (Session info: chrome=121.0.6167.161); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF66FEA5E42+3538674]
	(No symbol) [0x00007FF66FAC4C02]
	(No symbol) [0x00007FF66F975AEB]
	(No symbol) [0x00007FF66F9BBF4E]
	(No symbol) [0x00007FF66F9BC0CC]
	(No symbol) [0x00007FF66F9FE477]
	(No symbol) [0x00007FF66F9DF0EF]
	(No symbol) [0x00007FF66F9FBDE3]
	(No symbol) [0x00007FF66F9DEE53]
	(No symbol) [0x00007FF66F9AF514]
	(No symbol) [0x00007FF66F9B0631]
	GetHandleVerifier [0x00007FF66FED6CAD+3738973]
	GetHandleVerifier [0x00007FF66FF2C506+4089270]
	GetHandleVerifier [0x00007FF66FF24823+4057299]
	GetHandleVerifier [0x00007FF66FBF5C49+720121]
	(No symbol) [0x00007FF66FAD126F]
	(No symbol) [0x00007FF66FACC304]
	(No symbol) [0x00007FF66FACC432]
	(No symbol) [0x00007FF66FABBD04]
	BaseThreadInitThunk [0x00007FFDA8C9257D+29]
	RtlUserThreadStart [0x00007FFDA97CAA58+40]

In [3]:
from selenium.webdriver.common.keys import Keys
driver1 = webdriver.Chrome()
driver1.get("https://www.flipkart.com")

search_eng = driver1.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input")
search_eng.send_keys('sunglasses')
search = driver1.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input")
search.send_keys(Keys.ENTER)

In [65]:
brand = []
description = []

In [76]:
price = []

In [66]:
brand_n = driver1.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')

for i in brand_n:
    name = i.text
    brand.append(name)

clicknext = driver1.find_element(By.XPATH,"/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]")
clicknext.click()

time.sleep(2)
driver2 = webdriver.Chrome()
driver2.get('https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2')
brand_n2 = driver2.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')

for i in brand_n2:
    name = i.text
    brand.append(name)
    
clicknext = driver1.find_element(By.XPATH,"/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[12]")
clicknext.click()

driver3 = webdriver.Chrome()
driver3.get('https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=3')
brand_n3 = driver3.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
brand_n20 = brand_n3[:20]

for i in brand_n20:
    name = i.text
    brand.append(name)
    
brand

['VINCENT CHASE',
 'ROZZETTA CRAFT',
 'john jacobs',
 'john jacobs',
 'ROYAL SON',
 'AISLIN',
 'ROYAL SON',
 'Fastrack',
 'VINCENT CHASE',
 'IRUS',
 'ROYAL SON',
 'IDEE',
 'VINCENT CHASE',
 'ROYAL SON',
 'Vogue Eyewear',
 'GUESS',
 'OAKLEY',
 'OAKLEY',
 'Arnette',
 'Ann Taylor',
 'Lenskart Boost',
 'GANSTA',
 'IDEE',
 'GUESS',
 'Ann Taylor',
 'GUESS',
 'GUESS',
 'GUESS',
 'john jacobs',
 'GUESS',
 'john jacobs',
 'vogue',
 'GUESS',
 'SRPM',
 'john jacobs',
 'IRUS',
 'IDEE',
 'Ray-Ban',
 'GUESS',
 'IRUS',
 'OCHILA',
 'NuVew',
 'PIRASO',
 'ROYAL SON',
 'VINCENT CHASE',
 'Fastrack',
 'ROYAL SON',
 'Eyewearlabs',
 'PROVOGUE',
 'VINCENT CHASE',
 'Eyewearlabs',
 'AISLIN',
 'Elligator',
 'Mast & Harbour',
 'NuVew',
 'Singco India',
 'Eyewearlabs',
 'ROYAL SON',
 'Elligator',
 'RBGIIT',
 'ROYAL SON',
 'SYGA',
 'Fastrack',
 'Ray-Ban',
 'RESIST EYEWEAR',
 'ROZZETTA CRAFT',
 'ROYAL SON',
 'ROYAL SON',
 'Singco India',
 'Singco India',
 'ROYAL SON',
 'AISLIN',
 'VINCENT CHASE',
 'Fastrack',
 'PIRASO',
 'VINCENT CHASE',
 'ROYAL SON',
 'ROYAL SON',
 'Fastrack',
 'ROZZETTA CRAFT',
 'OCHILA',
 'NuVew',
 'Fastrack',
 'VINCENT CHASE',
 'ROZZETTA CRAFT',
 'VINCENT CHASE',
 'ROYAL SON',
 'Eyewearlabs',
 'Elligator',
 'PROVOGUE',
 'AISLIN',
 'ROYAL SON',
 'PC STAR',
 'VINCENT CHASE',
 'VINCENT CHASE',
 'VINCENT CHASE',
 'Eyewearlabs',
 'Eyewearlabs',
 'PIRASO',
 'ROZZETTA CRAFT']

In [67]:
description1 = driver1.find_elements(By.XPATH,'//a[@class="IRpwTa"]')

for i in description1:
    desc = i.text
    description.append(desc)

clicknext = driver1.find_element(By.XPATH,"/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]")
clicknext.click()

driver2 = webdriver.Chrome()
driver2.get('https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2')

description2 = driver2.find_elements(By.XPATH,'//a[@class="IRpwTa"]')

for i in description2:
    desc = i.text
    description.append(desc)
    
clicknext = driver1.find_element(By.XPATH,"/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[12]")
clicknext.click()

driver3 = webdriver.Chrome()
driver3.get('https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=3')
description3 = driver3.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
description20 = description3[:20]
for i in description20:
    desc = i.text
    description.append(desc)
    
print(len(description))

100

In [77]:
price_tags = driver1.find_elements(By.XPATH,'//div[@class="_30jeq3"]')

for i in price_tags:
    pri = i.text
    price.append(pri)

clicknext = driver1.find_element(By.XPATH,"/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[11]")
clicknext.click()

driver2 = webdriver.Chrome()
driver2.get('https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2')

price_tags = driver2.find_elements(By.XPATH,'//div[@class="_30jeq3"]')

for i in price_tags:
    pri = i.text
    price.append(pri)

clicknext = driver1.find_element(By.XPATH,"/html/body/div/div/div[3]/div[1]/div[2]/div[12]/div/div/nav/a[12]")
clicknext.click()

driver3 = webdriver.Chrome()
driver3.get('https://www.flipkart.com/search?q=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=3')

price_tags = driver1.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
price_tags20 = price_tags[:20]
for i in price_tags20:
    pri = i.text
    price.append(pri)
    
print(len(price))

100

In [78]:
print(len(brand),len(description),len(price))

100 100 100

In [79]:
df2 = pd.DataFrame({'BRAND':brand,'Desription':description,'PRICE':price})
df2

             BRAND                                         Desription    PRICE
0    VINCENT CHASE  by Lenskart Polarized, UV Protection Round Sun...     ₹949
1   ROZZETTA CRAFT   Polarized, UV Protection Aviator Sunglasses (55)     ₹467
2      john jacobs  UV Protection, Polarized Wayfarer Sunglasses (52)   ₹2,999
3      john jacobs             UV Protection Wayfarer Sunglasses (53)   ₹2,999
4        ROYAL SON    Polarized, UV Protection Sports Sunglasses (68)   ₹1,221
..             ...                                                ...      ...
95   VINCENT CHASE  by Lenskart Polarized, UV Protection Rectangul...   ₹4,079
96     Eyewearlabs     Polarized, UV Protection Round Sunglasses (47)  ₹10,387
97     Eyewearlabs  UV Protection Rectangular, Retro Square Sungla...   ₹6,528
98          PIRASO  by Lenskart Polarized, UV Protection Round Sun...   ₹3,639
99  ROZZETTA CRAFT  by Lenskart Polarized, UV Protection Retro Squ...   ₹2,499

[100 rows x 3 columns]

In [86]:
driveriph = webdriver.Chrome()
driveriph.get('https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market')

ModuleNotFoundError: No module named 'webdriver_manager'

In [93]:
rating =[]
rev_sum = []
full_rev = []

In [94]:
page_url = ['https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market','https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market=&page=2','https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market=&page=3','https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market=&page=4','https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market=&page=5','https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market=&page=6','https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market=&page=7','https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market=&page=8','https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market=&page=9','https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market=&page=10']

for i in page_url:
    driver = webdriver.Chrome()
    driver.get(i)
    rating_tags = driver.find_elements(By.XPATH,'//div[@class="_3LWZlK _1BLPMq"]')
    rev_sum_tags = driver.find_elements(By.XPATH,'//p[@class="_2-N8zT"]')
    full_rev_tags = driver.find_elements(By.XPATH,'//div[@class="t-ZTKy"]')
    for j in rating_tags:
        tags = j.text
        rating.append(tags)
    for j in rev_sum_tags:
        tags1 = j.text
        rev_sum.append(tags1)
    for j in full_rev_tags:
        tags2 = j.text
        full_rev.append(tags2)

print(len(rating),len(rev_sum),len(full_rev))

100 100 100

In [95]:
df4 = pd.DataFrame({'RATING':rating,'REVIEW SUMMARY':rev_sum,'FULL REVIEW':full_rev})
df4

,RATING,REVIEW SUMMARY,FULL REVIEW
0,5,Perfect product!,V Good all
1,5,Wonderful,This is amazing at all
2,5,Terrific,Very very good
3,5,Classy product,Camera is awesome\nBest battery backup\nA perf...
4,5,Best in the market!,Good Camera
...,...,...,...
95,5,Highly recommended,Thanks Flipkart For this amazing deal! I had a...
96,5,Wonderful,Excellent Fabulous Adorable Iphone 11 Value fo...
97,4,Very Good,I switched to IOS for long term use and for be...
98,5,Brilliant,Perfect iPhone on this budget!! Camera and the...
99,5,Classy product,Outstanding performance this phone

In [97]:
from selenium.webdriver.common.keys import Keys
driver1 = webdriver.Chrome()
driver1.get("https://www.flipkart.com")

search_eng = driver1.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input")
search_eng.send_keys('sneakers')
search = driver1.find_element(By.XPATH,"/html/body/div[1]/div/div[1]/div/div/div/div/div[1]/div/div[1]/div/div[1]/div[1]/header/div[1]/div[2]/form/div/div/input")
search.send_keys(Keys.ENTER)

In [121]:
brand = []
prod_desc = []
price = []

In [123]:
page_url = ['https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off','https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2','https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=3']

for i in page_url:
    driver = webdriver.Chrome()
    driver.get(i)
    brand_tags = driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
    price_tags = driver.find_elements(By.XPATH,'//div[@class="_30jeq3"]')
    
    for j in brand_tags:
        tags = j.text
        brand.append(tags)
    
    for j in price_tags:
        tags2 = j.text
        price.append(tags2)
    
    time.sleep(10)
        
print(len(brand),len(price))

120 120

In [122]:
page_url = ['https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=off&as=off','https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=2','https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=3','https://www.flipkart.com/search?q=sneakers&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=4']
for i in page_url:
    driver = webdriver.Chrome()
    driver.get(i)
    prod_desc_tags = driver.find_elements(By.XPATH,'//a[@class="IRpwTa"]')
    for j in prod_desc_tags:
        tags1 = j.text
        if tags1 is None:
            prod_desc.append('No Info')
        prod_desc.append(tags1)
        
print(len(prod_desc))

120

In [126]:
brand100 = brand[:100]
prod_desc100 = prod_desc[:100]
price100 = price[:100]

df5 = pd.DataFrame({'Brand':brand100,'Product Description':prod_desc100,'Price':price100})
df5

              Brand                                Product Description   Price
0            BRUTON           Exclusive Sneaker Shoes Sneakers For Men    ₹299
1             Krors  Mens Sneakers Shoes, Casual Shoes Sneakers For...    ₹444
2         Deals4you                                 Sneakers For Women    ₹299
3          URBANBOX  Trending Stylish Casual Outdoor Shoes Sneakers...    ₹299
4          RED TAPE  Casual Sneaker Shoes for Men | Soft Cushioned ...  ₹1,737
..              ...                                                ...     ...
95  U.S. POLO ASSN.  Mens Sneakers Shoes, Casual Shoes Sneakers For...  ₹1,339
96           BRUTON                             AURUN Sneakers For Men    ₹299
97     K' Footlance              Premium casual Shoes Sneakers For Men    ₹335
98  U.S. POLO ASSN.      Modern Trendy Sneakers Shoes Sneakers For Men  ₹1,339
99  U.S. POLO ASSN.  Stylish & Trending Outdoor Walking Comfortable...  ₹1,929

[100 rows x 3 columns]

In [141]:
from selenium.webdriver.common.keys import Keys
driver1 = webdriver.Chrome()
driver1.get("https://www.amazon.in/")

search_eng = driver1.find_element(By.ID,"twotabsearchtextbox")
search_eng.send_keys('laptop')
search = driver1.find_element(By.ID,"nav-search-submit-button")
search.click()

i7check = driver1.find_element(By.XPATH,"/html/body/div[1]/div[1]/div[1]/div[2]/div/div[3]/span/div[1]/div/div/div[8]/ul[19]/span/span[9]/li/span")
i7check.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="twotabsearchtextbox"]"}
  (Session info: chrome=121.0.6167.161); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF781955E42+3538674]
	(No symbol) [0x00007FF781574C02]
	(No symbol) [0x00007FF781425AEB]
	(No symbol) [0x00007FF78146BF4E]
	(No symbol) [0x00007FF78146C0CC]
	(No symbol) [0x00007FF7814AE477]
	(No symbol) [0x00007FF78148F0EF]
	(No symbol) [0x00007FF7814ABDE3]
	(No symbol) [0x00007FF78148EE53]
	(No symbol) [0x00007FF78145F514]
	(No symbol) [0x00007FF781460631]
	GetHandleVerifier [0x00007FF781986CAD+3738973]
	GetHandleVerifier [0x00007FF7819DC506+4089270]
	GetHandleVerifier [0x00007FF7819D4823+4057299]
	GetHandleVerifier [0x00007FF7816A5C49+720121]
	(No symbol) [0x00007FF78158126F]
	(No symbol) [0x00007FF78157C304]
	(No symbol) [0x00007FF78157C432]
	(No symbol) [0x00007FF78156BD04]
	BaseThreadInitThunk [0x00007FFDA8C9257D+29]
	RtlUserThreadStart [0x00007FFDA97CAA58+40]

In [143]:
driver1 = webdriver.Chrome()
driver1.get("https://www.azquotes.com/")

top_quotes = driver1.find_element(By.XPATH,"/html/body/div[1]/div[1]/div[1]/div/div[3]/ul/li[5]/a")
top_quotes.click()

In [147]:
quote = []
author = []
type_quo = []

In [148]:
page_url = ['https://www.azquotes.com/top_quotes.html',
           'https://www.azquotes.com/top_quotes.html?p=2',
           'https://www.azquotes.com/top_quotes.html?p=3',
           'https://www.azquotes.com/top_quotes.html?p=4',
           'https://www.azquotes.com/top_quotes.html?p=5',
           'https://www.azquotes.com/top_quotes.html?p=6',
           'https://www.azquotes.com/top_quotes.html?p=7',
           'https://www.azquotes.com/top_quotes.html?p=8',
           'https://www.azquotes.com/top_quotes.html?p=9',
           'https://www.azquotes.com/top_quotes.html?p=10']

for i in page_url:
    driver=webdriver.Chrome()
    driver.get(i)
    quote_tags = driver.find_elements(By.XPATH,'//a[@class="title"]')
    author_tags = driver.find_elements(By.XPATH,'//div[@class="author"]')
    type_tags = driver.find_elements(By.XPATH,'//div[@class="tags"]')
    for j in quote_tags:
        tags = j.text
        quote.append(tags)
    
    for j in author_tags:
        tags1 = j.text
        author.append(tags1)
    
    for j in type_tags:
        tags2 = j.text
        type_quo.append(tags2)
    
print(len(quote),len(author),len(type_quo))

1000 1000 1000

In [151]:
df6 = pd.DataFrame({'Quote':quote,'Author':author,'Quote Type':type_quo})
df6

,Quote,Author,Quote Type
0,The essence of strategy is choosing what not t...,Michael Porter,"Essence, Deep Thought, Transcendentalism"
1,One cannot and must not try to erase the past ...,Golda Meir,"Inspiration, Past, Trying"
2,Patriotism means to stand by the country. It d...,Theodore Roosevelt,"Country, Peace, War"
3,Death is something inevitable. When a man has ...,Nelson Mandela,"Inspirational, Motivational, Death"
4,You have to love a nation that celebrates its ...,Erma Bombeck,"4th Of July, Food, Patriotic"
...,...,...,...
995,Regret for the things we did can be tempered b...,Sydney J. Harris,"Love, Inspirational, Motivational"
996,America... just a nation of two hundred millio...,Hunter S. Thompson,"Gun, Two, Qualms About"
997,For every disciplined effort there is a multip...,Jim Rohn,"Inspirational, Greatness, Best Effort"
998,"The spiritual journey is individual, highly pe...",Ram Dass,"Spiritual, Truth, Yoga"
999,The mind is not a vessel to be filled but a fi...,Plutarch,"Inspirational, Leadership, Education"

In [158]:
driverpm = webdriver.Chrome()
driverpm.get("https://www.jagranjosh.com/")

click_gk = driverpm.find_element(By.XPATH,'/html/body/div/header/nav/div/div/div[3]/ul/li[3]/a')
click_gk.click()

driverpmgk =webdriver.Chrome()
driverpmgk.get("https://www.jagranjosh.com/general-knowledge")

explore = driverpmgk.find_element(By.XPATH,'/html/body/div[1]/div[8]/section[5]/div[1]/span/a')
explore.click()

drivpm =webdriver.Chrome()
drivpm.get("https://www.jagranjosh.com/general-knowledge-india-an-overview-1291979784-1")

list_pm = drivpm.find_element(By.XPATH,'/html/body/div[1]/main/div[1]/div[1]/section[2]/div/ul/li[11]/article/h3/a')
list_pm.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[8]/section[5]/div[1]/span/a"}
  (Session info: chrome=121.0.6167.161); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF781955E42+3538674]
	(No symbol) [0x00007FF781574C02]
	(No symbol) [0x00007FF781425AEB]
	(No symbol) [0x00007FF78146BF4E]
	(No symbol) [0x00007FF78146C0CC]
	(No symbol) [0x00007FF7814AE477]
	(No symbol) [0x00007FF78148F0EF]
	(No symbol) [0x00007FF7814ABDE3]
	(No symbol) [0x00007FF78148EE53]
	(No symbol) [0x00007FF78145F514]
	(No symbol) [0x00007FF781460631]
	GetHandleVerifier [0x00007FF781986CAD+3738973]
	GetHandleVerifier [0x00007FF7819DC506+4089270]
	GetHandleVerifier [0x00007FF7819D4823+4057299]
	GetHandleVerifier [0x00007FF7816A5C49+720121]
	(No symbol) [0x00007FF78158126F]
	(No symbol) [0x00007FF78157C304]
	(No symbol) [0x00007FF78157C432]
	(No symbol) [0x00007FF78156BD04]
	BaseThreadInitThunk [0x00007FFDA8C9257D+29]
	RtlUserThreadStart [0x00007FFDA97CAA58+40]

In [162]:
driverpmgk =webdriver.Chrome()
driverpmgk.get("https://www.jagranjosh.com/general-knowledge")

explore = driverpmgk.find_element(By.XPATH,'/html/body/div[1]/div[8]/section[9]/ul/li[6]/a')
explore.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div[8]/section[9]/ul/li[6]/a"}
  (Session info: chrome=121.0.6167.161); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF781955E42+3538674]
	(No symbol) [0x00007FF781574C02]
	(No symbol) [0x00007FF781425AEB]
	(No symbol) [0x00007FF78146BF4E]
	(No symbol) [0x00007FF78146C0CC]
	(No symbol) [0x00007FF7814AE477]
	(No symbol) [0x00007FF78148F0EF]
	(No symbol) [0x00007FF7814ABDE3]
	(No symbol) [0x00007FF78148EE53]
	(No symbol) [0x00007FF78145F514]
	(No symbol) [0x00007FF781460631]
	GetHandleVerifier [0x00007FF781986CAD+3738973]
	GetHandleVerifier [0x00007FF7819DC506+4089270]
	GetHandleVerifier [0x00007FF7819D4823+4057299]
	GetHandleVerifier [0x00007FF7816A5C49+720121]
	(No symbol) [0x00007FF78158126F]
	(No symbol) [0x00007FF78157C304]
	(No symbol) [0x00007FF78157C432]
	(No symbol) [0x00007FF78156BD04]
	BaseThreadInitThunk [0x00007FFDA8C9257D+29]
	RtlUserThreadStart [0x00007FFDA97CAA58+40]

In [172]:
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome()
driver.get("https://www.motor1.com/")

search_eng = driver.find_element(By.ID,"search_input")
search_eng.click()
search_eng.send_keys('50 most expensive cars')
search_eng.send_keys(Keys.ENTER)

time.sleep(2)
exp_cars = driver.find_element(By.XPATH,'/html/body/div[10]/div[9]/div/div[1]/div/div/div[2]/div/div[1]/h3/a')
exp_cars.click()

In [194]:
company = []
price = []

In [195]:
company_tags = driver.find_elements(By.XPATH,'//h3[@class="subheader"]')

for i in company_tags:
    tags = i.text
    company.append(tags)
    
price_tags = driver.find_elements(By.XPATH,'//strong')

for i in price_tags:
    tags = i.text
    price.append(tags)
company50 = company[:50]
print(len(company50),len(price))

50 50

In [196]:
df7 = pd.DataFrame({'Company':company50,'Price':price})
df7

                               Company                        Price
0                  Aston Martin Valour          Price: $1.5 Million
1                         McLaren Elva          Price: $1.7 Million
2                          Czinger 21C          Price: $1.7 Million
3                        Ferrari Monza          Price: $1.7 Million
4                   Gordon Murray T.33          Price: $1.7 Million
5                    Koenigsegg Gemera          Price: $1.7 Million
6                          Zenvo TSR-S          Price: $1.7 Million
7                   Hennessey Venom F5          Price: $1.8 Million
8                      Bentley Bacalar          Price: $1.9 Million
9        Hispano Suiza Carmen Boulogne          Price: $1.9 Million
10              Bentley Mulliner Batur          Price: $2.0 Million
11                        Deus Vayanne          Price: $2.0 Million
12                         SSC Tuatara          Price: $2.0 Million
13                         Lotus Evija          Price: $2.1 Million
14                 Aston Martin Vulcan          Price: $2.3 Million
15                          Delage D12          Price: $2.3 Million
16                 Ferrari Daytona SP3          Price: $2.3 Million
17                   McLaren Speedtail          Price: $2.3 Million
18                        Rimac Nevera          Price: $2.4 Million
19                       Pagani Utopia          Price: $2.5 Million
20                Pininfarina Battista          Price: $2.5 Million
21                  Gordon Murray T.50          Price: $2.6 Million
22                Lamborghini Countach          Price: $2.6 Million
23            Mercedes-AMG Project One          Price: $2.7 Million
24                        Zenvo Aurora          Price: $2.8 Million
25                 Aston Martin Victor          Price: $3.0 Million
26         Hennessey Venom F5 Roadster                 $3.0 Million
27                    Koenigsegg Jesko          Price: $3.0 Million
28               Aston Martin Valkyrie          Price: $3.2 Million
29           W Motors Lykan Hypersport          Price: $3.4 Million
30                       McLaren Solus                 $3.5 Million
31                    Lamborghini Sian          Price: $3.6 million
32                    Koenigsegg CC850          Price: $3.7 Million
33     Bugatti Chiron Super Sport 300+          Price: $3.9 Million
34                  Lamborghini Veneno          Price: $4.5 Million
35                      Bugatti Bolide          Price: $4.7 Million
36           Pininfarina B95 Speedster          Price: $4.8 Million
37                     Bugatti Mistral          Price: $5.0 Million
38                 Pagani Huayra Imola          Price: $5.4 Million
39                        Bugatti Divo          Price: $5.8 Million
40                 SP Automotive Chaos          Price: $6.4 Million
41                    Pagani Codalunga          Price: $7.4 Million
42                        777 Hypercar          Price: $7.5 Million
43            Mercedes-Maybach Exelero          Price: $8.0 Million
44                  Bugatti Centodieci          Price: $9.0 Million
45             Bugatti Chiron Profilée         Price: $10.8 Million
46                Rolls-Royce Sweptail         Price: $12.8 Million
47            Bugatti La Voiture Noire         Price: $13.4 Million
48              Rolls-Royce Boat Tail*  Price: $28.0 Million (est.)
49  Rolls-Royce La Rose Noire Droptail    Price: $30 Million (est.)